### PR TITLE
4xBit

### PR DESCRIPTION
**Pull request by mybtcfx**

### CODE REVIEW

**Comment by magichatsam** [comment]
Have merged this for you here: https://github.com/saturn-network/assets/commit/19ad48eb938d3c5cf48f51215bd43c7ca0421917

Forum is for an announcement post to introduce your token to our community on our Forum: https://forum.saturn.network it is not for your telegram group, I would recommend you create one, thanks!

Also we can assist you with promotional airdrops to active traders on our platform, currently over 1400 wallets. Please fill in this form if you would like to discuss https://forms.gle/QjtUYcbttCeyUfK48

Hope to see an active 4Bit/ETH market soon 👍 welcome!

**Comment by mybtcfx** [comment]
Hello Sam
Thank you for the information.
its good to hear from you that we have listed is Saturn Network.
at present, I have seen two issues.
1) MetaMask - RPC Error: gas required exceeds allowance (9941175) or always
failing transaction
2) image is not reflecting in exchange
https://github.saturn.network/eth/logo/4xBIT.png

Kindly let me know do I need to modify anything in our end.
Thank you again.
Have a nice day

**Comment by magichatsam** [comment]
Great to see you have completed your listing, I have fixed your logo it will be displayed shortly on the exchange. For MetaMask, that is odd, have you approved our website under connections in the settings? I would need some examples of failed transaction to investigate.

Personally I use Saturn Wallet or Nifty Wallet: http://www.saturn.network/blog/compatible-dapp-browsers-saturn-exchange/

**Comment by mybtcfx** [comment]
appreciate your response
Yes, I approved www.saturn.network in metamask.
This is the network error detail I am getting
MetaMask - RPC Error: gas required exceeds allowance (9960462) or always
failing transaction {code: -32000, message: "gas required exceeds allowance
(9960462) or always failing transaction"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
i._write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
W @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
_write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
W @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
_write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
W @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
i._onMessage @ contentscript.js:1

**Pull request closed without merging**
